name: Danger

on:
  pull_request:
    branches:
      - main

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v2
        with:
          ruby-version: '3.0'
      - run: gem install danger
      - run: danger